[package]
name = "flannning_app"
version = "0.0.1"
edition = "2021"

[dependencies]
actix-web = "4.9"
actix-service = "2.0"
actix-session = { version = "0.10", features = ["cookie-session"] }
actix-web-httpauth = "0.8"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.10", features = ["v4", "serde"] }
diesel = { version = "2.2", features = ["postgres", "r2d2", "chrono", "uuid"] }
dotenvy = "0.15"
env_logger = "0.11"
jsonwebtoken = "9.3"
bcrypt = "0.15"
validator = "0.18"
lazy_static = "1.5"
