[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.13"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.40", features = ["full"] }
serde_json = "1.0"

services = { path = "../../libs/services" }
aws_lambda_events = "0.15.1"
http = "1.1.0"
